name: format

on:
  pull_request:
    branches: [main, master, develop]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', '**.cmake', '.github/workflows/format.yml']
  push:
    branches: [main, master, develop]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', '**.cmake', '.github/workflows/format.yml']

concurrency:
  group: ${{ github.workflow }}-linux-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git cmake ninja-build libwayland-dev libwayland-egl-backend-dev wayland-protocols libxkbcommon-dev libegl1-mesa-dev libcairo2-dev libmpv-dev clang clang-tidy clang-tools libpam0g-dev libudev-dev wget cmake-format clang-format libdrm-dev

      - name: configure
        run: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug -DENABLE_TEST=OFF

      - name: format
        run: cmake --build build --target fix-format

      - name: show diff
        run: git diff --color --exit-code
